### ISSUE TITLE
The Secure Spreadsheets Editor isn't supported

### ISSUE THREAD

**Issue by JaspalSuri** [Lissy93/callisto-theme-standard-notes#1]
Hi @Lissy93,

I just wanted to say thanks for creating this theme! I've been using since you've shared it and it looks great. 🙂 

I noticed that the theme currently doesn't support the Secure Spreadsheets Editor in the sense that the cells are white and the text is grey. Is this intentional, given that the cells can be formatted with different background colors?

**Comment by lissy93** [comment]
Good spot, I put the wrong variable name in - thanks for pointing it out, I've fixed it in dd3ef354839c065ac4ef49aee4a8edbe979955e5 :)

**Comment by JaspalSuri** [comment]
Thank you for fixing it!
