### ISSUE TITLE
Error importing theme

### ISSUE THREAD

**Issue by Quarmire** [Lissy93/callisto-theme-standard-notes#6]
When I try to import the theme on the desktop app, the 'Install' button does not work and the fields are left empty.  An image is attached for reference.

![image](https://user-images.githubusercontent.com/28873711/141825087-94add0e1-14b7-4857-a559-e770f1706dc0.png)

**Comment by Quarmire** [comment]
It seems that this link is broken: https://github.com/Lissy93/callisto-theme-standard-notes/archive/1.0.3.zip

**Comment by lissy93** [comment]
Heya @Quarmire 
Try with this link: `https://notes.aliciasykes.com/p/9Nggclsf0G`
Testing it out, and it looks like the SN returns a CORS error for the GH link. Let me know if that works for you, and I'll update the docs :)

**Comment by Quarmire** [comment]
Thank you @Lissy93 
The link imported perfectly!
